version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "[fileforge]"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ["*"]
    commit-message:
      prefix: "[fileforge]"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
    commit-message:
      prefix: "[fileforge]"
